Upgraded to rdc 1.0.3 and fixed breaking errors
cthit/HowTo pull request #32
Opened 2021-05-20 10:21 UTC by Hoidi

Thanks @molleer

2021-05-20 10:22 UTC, molleer commented
No problem 👉😎👉

2021-05-20 10:24 UTC, Hoidi commented
Saknar digIT merge privilegier :(

2021-05-20 11:28 UTC, molleer commented
The markdown does not seem to work properly
![bild](https://user-images.githubusercontent.com/31804935/118970931-1c2aaf80-b96f-11eb-8865-89c8b44c7f11.png)
@Hoidi  Do still this is ok, or should this be fixed first?
@Portals Any idea what is wrong with the `DigitMarkdown` component?

2021-05-20 11:56 UTC, Hoidi commented
> The markdown does not seem to work properly
Thought it was just that I didn't have the right fonts or something :(

2021-05-20 12:01 UTC, Portals commented
DigitMarkdown is a bit of a mess. Please create an issue on the RDC repo.

2021-05-20 12:06 UTC, Portals requested changes

2021-05-20 12:06 UTC, Portals commented on frontend/package.json
> +        "@cthit/react-digit-components": "^1.0.3",
You need to update the dependencies that RDC v1.0.3 needs.

For example, redux is needed at all.

2021-05-20 12:06 UTC, Portals commented on frontend/src/components/elements/tutorial/index.jsx
> +                            <div>
Unnecessary div?

2021-05-20 12:06 UTC, Portals commented on frontend/src/components/elements/tutorial/index.jsx
> +                            <div>
A fragment can be used instead.

2021-05-20 12:30 UTC, molleer approved these changes
I think it is ok. Better that it looks bad that there being wrong information.

2021-05-20 12:33 UTC, Portals commented
Still incorrect dependencies:
https://github.com/cthit/react-digit-components/releases/tag/v1.0.3

2021-05-24 11:30 UTC, Portals approved these changes

2021-05-24 11:32 UTC, merged